# -*- coding: utf-8 -*-
# [#126/#127] Content table for the mission-tree expansion: every Qing mission tree must
# reach >= 20 tasks (#127), and the two flagged trees (New Treasure Fleet, Contest the
# Company) must roughly DOUBLE (#126). These are "breadth" flavour tasks in the PROVEN
# idiom already shipped for qing_india_maratha/sikh/trade/himalaya_road:
#
#     <key> = {
#         icon = <key>
#         requires = { <opening_task> }
#         allow = { <political_influence|treasury> >= N }
#         on_start = { add_political_influence|add_treasury = -N }
#         on_completion = {
#             custom_tooltip = <key>_tt
#             current_ruler = { add_popularity = P }
#             [ add_stability = 1 ]
#             LOG_line = { sys = QING  msg = "MISSION task <key> for" }
#         }
#     }
#
# ZERO new modifiers / scripted effects are introduced (that is the #133 undefined-effect
# trap). Only country-scope engine effects already used throughout the suite: add_popularity
# (on current_ruler), add_stability, add_treasury, add_political_influence, custom_tooltip,
# LOG_line. gen_mission_tasks.py consumes this table to (a) splice the task blocks in before
# each tree's closing brace, (b) append the 3 loc keys (<key>, <key>_DESC, <key>_tt) to the
# tree's english yml, and (c) surface the curated period-art query. gen_mission_icons.py then
# fetches + converts the DX10 icon for each new <key>.
#
# Each task: (key, cjk, en, desc, tt, cost, pop, stab, query)
#   cost = None | ("pol", n) | ("trs", n)   -> the allow/on_start resource gate
#   pop  = add_popularity on current_ruler
#   stab = True adds add_stability = 1 (reserve for the culminating breadth task)
#   query= Wikimedia Commons period-art search (see fetch_wm._art_score)


class T:
    __slots__ = ("key", "cjk", "en", "desc", "tt", "cost", "pop", "stab", "query")

    def __init__(self, key, cjk, en, desc, tt, cost, pop, stab, query):
        self.key = key
        self.cjk = cjk
        self.en = en
        self.desc = desc
        self.tt = tt
        self.cost = cost
        self.pop = pop
        self.stab = stab
        self.query = query


TREES = {
    # ================================================================= #126 =
    "treasure_fleet": {
        "loc": "qing_treasure_fleet_l_english.yml",
        "parent": "qing_treasure_revive_yards",
        "tasks": [
            T("qing_treasure_shipwrights", "船匠營", "The Master Shipwrights",
              "Gather the master shipwrights of Fujian and Longjiang, whose fathers built the great treasure ships. Costs #Y 25#! political influence.",
              "The master shipwrights of Fujian are gathered to the imperial yards.",
              ("pol", 25), 10, False, "Ming dynasty junk ship painting"),
            T("qing_treasure_teak", "柚木採辦", "The Teak Trade",
              "Secure the teak and ironwood of the southern seas for the fleet's keels and hulls. Costs #Y 60#! treasury.",
              "The teak forests of the south seas supply the imperial keels.",
              ("trs", 60), 10, False, "Burma landscape 19th century painting"),
            T("qing_treasure_compass", "羅盤司", "The Compass Bureau",
              "Charter the compass-masters' bureau, keepers of the wet-needle and the star-lore of the sea. Costs #Y 25#! political influence.",
              "The compass-masters' bureau keeps the fleet's bearings.",
              ("pol", 25), 10, False, "compass rose old map"),
            T("qing_treasure_marines", "水師陸戰", "The Fleet Marines",
              "Raise the marine companies that storm the shore where the treasure ships anchor. Costs #Y 55#! treasury.",
              "The fleet's marine companies stand ready to storm any shore.",
              ("trs", 55), 11, False, "Ming dynasty soldiers painting"),
            T("qing_treasure_grain_tribute", "漕糧海運", "The Sea-Route Grain Tribute",
              "Turn the Grand Canal's grain tribute to the ocean route, and the sea-lanes fill with imperial hulls. Costs #Y 65#! treasury.",
              "The grain tribute rides the ocean route, and the sea-lanes teem with hulls.",
              ("trs", 65), 10, False, "Grand Canal China historical painting"),
            T("qing_treasure_quanzhou", "刺桐復港", "The Revival of Zaiton",
              "Revive Quanzhou, the Zaiton of Marco Polo's wonder, greatest of the old China ports. Costs #Y 60#! treasury.",
              "Quanzhou, the Zaiton of old, is a great port once more.",
              ("trs", 60), 11, False, "Fujian coast historical map"),
            T("qing_treasure_guangzhou", "廣州市舶", "The Canton Maritime Office",
              "Restore the maritime-trade office at Canton to fit out and provision the voyages. Costs #Y 55#! treasury.",
              "The Canton maritime office fits out the treasure voyages.",
              ("trs", 55), 10, False, "Canton factories painting"),
            T("qing_treasure_ryukyu_pilots", "琉球引水", "The Ryukyu Pilots",
              "Take on the Ryukyu pilots and their inherited sea-lore of the eastern ocean. Costs #Y 20#! political influence.",
              "The Ryukyu pilots lend their sea-lore to the imperial fleet.",
              ("pol", 20), 10, False, "Ryukyu kingdom ship historical painting"),
            T("qing_treasure_spice", "香料貿易", "The Spice Trade",
              "Open the spice trade of the southern archipelago to the treasure fleet's holds. Costs #Y 60#! treasury.",
              "The spice trade of the southern seas fills the fleet's holds.",
              ("trs", 60), 10, False, "Moluccas historical map"),
            T("qing_treasure_giraffe", "麒麟入貢", "The Tribute Qilin",
              "Bring home the tribute-giraffe of Bengal, hailed at court as the auspicious qilin. Costs #Y 20#! political influence.",
              "The tribute-giraffe of Bengal is hailed at court as the qilin.",
              ("pol", 20), 12, False, "Shen Du giraffe painting Ming"),
            T("qing_treasure_charts_south", "針路南洋", "The Southern Sailing Directions",
              "Compile the needle-route sailing directions for the whole of the southern ocean. Costs #Y 25#! political influence.",
              "The needle-route directions chart the whole southern ocean.",
              ("pol", 25), 10, False, "Zheng He navigation map Mao Kun"),
            T("qing_treasure_drydock", "龍江船塢", "The Longjiang Drydocks",
              "Rebuild the great drydocks of Longjiang, where a treasure ship could be laid down whole. Costs #Y 70#! treasury.",
              "The great drydocks of Longjiang lay down whole treasure ships.",
              ("trs", 70), 11, False, "Chinese junk painting"),
            T("qing_treasure_astronomers", "觀星定向", "The Star-Reading Astronomers",
              "Attach the astronomers of the Directorate to the fleet, to fix its course by the stars. Costs #Y 25#! political influence.",
              "The Directorate's astronomers fix the fleet's course by the stars.",
              ("pol", 25), 10, False, "Chinese astronomy instrument historical illustration"),
            T("qing_treasure_admiralty", "寶船提督", "The Treasure-Fleet Admiralty",
              "Establish the admiralty of the treasure fleet, a standing command over the ocean-going navy. Costs #Y 80#! treasury.",
              "The admiralty of the treasure fleet commands the ocean-going navy.",
              ("trs", 80), 15, True, "Zheng He treasure ship"),
        ],
    },
    "india": {
        "loc": "qing_india_l_english.yml",
        "parent": "qing_india_descent",
        "tasks": [
            T("qing_india_hyderabad", "通海德拉巴", "The Nizam of Hyderabad",
              "Open relations with the Nizam of Hyderabad, the greatest of the Deccan princes. Costs #Y 25#! political influence.",
              "The Nizam of Hyderabad receives the Son of Heaven's envoys.",
              ("pol", 25), 11, False, "Nizam of Hyderabad miniature painting"),
            T("qing_india_mysore", "結邁索爾", "The Tiger of Mysore",
              "Make common cause with Mysore, whose sultans wage their own war on the Company. Costs #Y 25#! political influence.",
              "Mysore joins the cause against the Company.",
              ("pol", 25), 12, False, "Tipu Sultan Mysore painting"),
            T("qing_india_rohilla", "羅希拉", "The Rohilla Afghans",
              "Court the Rohilla Afghan chieftains of the doab against the Company's advance. Costs #Y 20#! political influence.",
              "The Rohilla Afghans of the doab are courted to the cause.",
              ("pol", 20), 10, False, "Mughal cavalry miniature painting"),
            T("qing_india_awadh", "撫奧德", "The Nawab of Awadh",
              "Reach the Nawab of Awadh, whose Lucknow court the Company would bleed white. Costs #Y 25#! political influence.",
              "The Nawab of Awadh at Lucknow inclines to the Son of Heaven.",
              ("pol", 25), 11, False, "Nawab of Awadh Lucknow miniature painting"),
            T("qing_india_deccan", "南印通商", "The Deccan Trade",
              "Open the overland trade to the Deccan plateau and its fortress-kingdoms. Costs #Y 60#! treasury.",
              "The overland trade to the Deccan is opened.",
              ("trs", 60), 10, False, "Deccan sultanate historical painting"),
            T("qing_india_coromandel", "科羅曼德", "The Coromandel Coast",
              "Contest the Coromandel ports where the western companies keep their factories. Costs #Y 60#! treasury.",
              "The Coromandel ports are contested with the western companies.",
              ("trs", 60), 10, False, "Coromandel coast historical map 18th century"),
            T("qing_india_malabar", "馬拉巴海岸", "The Malabar Pepper Coast",
              "Take a share of the Malabar pepper coast, the spice-wealth of the western shore. Costs #Y 60#! treasury.",
              "A share of the Malabar pepper trade is secured.",
              ("trs", 60), 10, False, "Malabar coast historical map 18th century"),
            T("qing_india_ceylon", "錫蘭", "The Island of Ceylon",
              "Reach across the strait to the cinnamon-island of Ceylon. Costs #Y 65#! treasury.",
              "The cinnamon-island of Ceylon is drawn into the sphere.",
              ("trs", 65), 10, False, "Kandy Ceylon historical"),
            T("qing_india_afghan", "阿富汗通道", "The Afghan Passes",
              "Treat with the Durrani Afghans who hold the northwest passes into Hindustan. Costs #Y 25#! political influence.",
              "The Durrani Afghans open the northwest passes.",
              ("pol", 25), 11, False, "Durrani empire Afghan painting"),
            T("qing_india_ganges_fleet", "恆河舟師", "The Ganges River Fleet",
              "Float a river fleet on the sacred Ganges, master of the artery of Hindustan. Costs #Y 80#! treasury.",
              "A river fleet masters the artery of the Ganges.",
              ("trs", 80), 14, True, "Ganges river boats painting"),
        ],
    },
    # ================================================================= #127 =
    "burma_war": {
        "loc": "qing_burma_war_l_english.yml",
        "parent": "qing_burma_mobilise",
        "tasks": [
            T("qing_burma_green_standard", "綠營南征", "The Green Standard Marches",
              "Muster the Green Standard armies of the south for the descent on the Konbaung realm. Costs #Y 55#! treasury.",
              "The Green Standard armies march south into Burma.",
              ("trs", 55), 11, False, "Qing dynasty soldiers painting"),
            T("qing_burma_manchu_bannermen", "滿洲勁旅", "The Manchu Banner Elite",
              "Send down the Manchu banner elite to stiffen the frontier host. Costs #Y 60#! treasury.",
              "The Manchu banner elite stiffen the frontier host.",
              ("trs", 60), 11, False, "Manchu bannerman Qing painting"),
            T("qing_burma_irrawaddy", "伊洛瓦底", "The Irrawaddy Road",
              "Force the Irrawaddy river road, the spine of the Burmese kingdom. Costs #Y 60#! treasury.",
              "The Irrawaddy river road is forced.",
              ("trs", 60), 10, False, "Irrawaddy river Burma"),
            T("qing_burma_kachin", "克欽山地", "The Kachin Hills",
              "Win over the Kachin hill peoples who hold the ridges above the valley. Costs #Y 20#! political influence.",
              "The Kachin hill peoples come over to the imperial standard.",
              ("pol", 20), 10, False, "Kachin hills Burma historical illustration"),
            T("qing_burma_laos", "老撾屬邦", "The Lao Principalities",
              "Bring the Lao principalities of the Mekong under the wing. Costs #Y 20#! political influence.",
              "The Lao principalities bend to the Son of Heaven.",
              ("pol", 20), 10, False, "Lan Xang Laos kingdom historical"),
            T("qing_burma_siam_flank", "暹羅側翼", "The Siamese Flank",
              "Turn Siam upon the Burmese flank, old foe of the Konbaung kings. Costs #Y 25#! political influence.",
              "Siam presses the Burmese flank.",
              ("pol", 25), 11, False, "Siam Ayutthaya kingdom historical painting"),
            T("qing_burma_teak", "緬甸柚木", "The Teak Forests",
              "Seize the teak forests of the Burmese uplands for the imperial dockyards. Costs #Y 55#! treasury.",
              "The teak forests of Burma feed the imperial dockyards.",
              ("trs", 55), 10, False, "Burma landscape 19th century painting"),
            T("qing_burma_jade_mines", "玉石礦", "The Jade Mines",
              "Take the jade mines of Upper Burma, source of the imperial court's green stone. Costs #Y 60#! treasury.",
              "The jade mines of Upper Burma pass to the throne.",
              ("trs", 60), 10, False, "Chinese jade carving Qing museum"),
            T("qing_burma_monsoon", "避瘴待時", "Await the Monsoon's Turn",
              "Hold the host through the fever-season and strike when the monsoon turns. Costs #Y 20#! political influence.",
              "The host waits out the fevers and strikes when the season turns.",
              ("pol", 20), 10, False, "Qianlong campaign copperplate engraving battle"),
            T("qing_burma_pacify", "綏靖邊陲", "Pacify the Frontier",
              "Set a lasting order on the pacified southern frontier. Costs #Y 70#! treasury.",
              "A lasting order is set on the southern frontier.",
              ("trs", 70), 14, True, "Victory banquet Qianlong campaign painting"),
        ],
    },
    "central_asia": {
        "loc": "qing_central_asia_l_english.yml",
        "parent": "qing_ca_beyond_pass",
        "tasks": [
            T("qing_ca_dzungar_remnant", "準噶爾餘部", "The Dzungar Remnant",
              "Run down the last Dzungar bands scattered across the steppe. Costs #Y 55#! treasury.",
              "The last Dzungar bands are run down on the steppe.",
              ("trs", 55), 11, False, "Pacification of Dzungars copperplate engraving"),
            T("qing_ca_torghut", "土爾扈特歸", "The Return of the Torghut",
              "Receive the Torghut Mongols home from the Volga to the imperial pastures. Costs #Y 25#! political influence.",
              "The Torghut Mongols are received home from the Volga.",
              ("pol", 25), 12, False, "Mongol nomad painting"),
            T("qing_ca_kashgar", "喀什噶爾", "The Oasis of Kashgar",
              "Take Kashgar, the great western oasis of the Tarim rim. Costs #Y 60#! treasury.",
              "Kashgar, the western oasis, is taken.",
              ("trs", 60), 10, False, "Kashgar historical"),
            T("qing_ca_yarkand", "葉爾羌", "Yarkand",
              "Bring Yarkand and its caravan wealth under the Ili general's writ. Costs #Y 55#! treasury.",
              "Yarkand and its caravan wealth submit.",
              ("trs", 55), 10, False, "Yarkand historical"),
            T("qing_ca_khotan", "和闐玉", "The Jade of Khotan",
              "Master Khotan, whose rivers yield the finest jade of the empire. Costs #Y 60#! treasury.",
              "Khotan and its jade rivers pass to the throne.",
              ("trs", 60), 10, False, "jade carving Chinese"),
            T("qing_ca_kokand", "浩罕汗國", "The Khanate of Kokand",
              "Treat with the Khanate of Kokand beyond the western passes. Costs #Y 25#! political influence.",
              "The Khanate of Kokand accepts the caravan accord.",
              ("pol", 25), 10, False, "Kokand khanate Central Asia historical"),
            T("qing_ca_bukhara", "布哈拉", "Bukhara the Noble",
              "Open the road to Bukhara, ancient seat of learning on the Silk Road. Costs #Y 25#! political influence.",
              "The road to Bukhara is opened.",
              ("pol", 25), 10, False, "Bukhara historical"),
            T("qing_ca_tarbagatai", "塔爾巴哈台", "The Tarbagatai Passes",
              "Hold the Tarbagatai passes onto the Kazakh steppe. Costs #Y 55#! treasury.",
              "The Tarbagatai passes are held.",
              ("trs", 55), 10, False, "Central Asia steppe historical map 19th century"),
            T("qing_ca_muslim_begs", "回部伯克", "The Muslim Begs",
              "Confirm the Muslim begs as the throne's officers over the oasis towns. Costs #Y 20#! political influence.",
              "The Muslim begs govern the oases as the throne's officers.",
              ("pol", 20), 10, False, "Uyghur historical"),
            T("qing_ca_garrison_cities", "滿城駐防", "The Garrison Cities",
              "Raise the walled Manchu garrison cities that anchor the western dominion. Costs #Y 70#! treasury.",
              "The Manchu garrison cities anchor the western dominion.",
              ("trs", 70), 14, True, "Qing empire historical map 18th century"),
        ],
    },
    "himalaya_seasia": {
        "loc": "qing_himalaya_seasia_l_english.yml",
        "parent": "qing_hs_lifanyuan",
        "tasks": [
            T("qing_hs_bhutan", "不丹", "The Kingdom of Bhutan",
              "Take the Druk realm of Bhutan into the tributary sphere. Costs #Y 20#! political influence.",
              "Bhutan enters the tributary sphere.",
              ("pol", 20), 10, False, "Bhutan dzong historical"),
            T("qing_hs_sikkim", "錫金", "The Kingdom of Sikkim",
              "Bring Sikkim, gate of the eastern Himalaya, under the wing. Costs #Y 20#! political influence.",
              "Sikkim, gate of the eastern Himalaya, submits.",
              ("pol", 20), 10, False, "Sikkim historical"),
            T("qing_hs_ladakh", "拉達克", "The Kingdom of Ladakh",
              "Reach Ladakh, the little Tibet astride the western passes. Costs #Y 25#! political influence.",
              "Ladakh, the little Tibet, inclines to Peking.",
              ("pol", 25), 10, False, "Ladakh monastery historical"),
            T("qing_hs_gorkha", "廓爾喀", "The Gorkha War",
              "Answer the Gorkha of Nepal, who raid Tibet, with the frontier armies. Costs #Y 60#! treasury.",
              "The Gorkha of Nepal are chastised on the Tibetan frontier.",
              ("trs", 60), 12, False, "Nepal Gurkha soldier historical"),
            T("qing_hs_assam", "阿薩姆", "The Ahom of Assam",
              "Open relations with the Ahom kingdom of the Brahmaputra valley. Costs #Y 20#! political influence.",
              "The Ahom of Assam receive the imperial envoys.",
              ("pol", 20), 10, False, "Ahom kingdom Assam historical"),
            T("qing_hs_manipur", "曼尼普爾", "The Manipur Marches",
              "Draw Manipur, hinge of the Burma-India marches, into the sphere. Costs #Y 20#! political influence.",
              "Manipur enters the tributary sphere.",
              ("pol", 20), 10, False, "Manipur kingdom historical illustration"),
            T("qing_hs_arakan", "阿拉干", "The Arakan Coast",
              "Contest the Arakan coast along the eastern bay. Costs #Y 55#! treasury.",
              "The Arakan coast is drawn into the sphere.",
              ("trs", 55), 10, False, "Arakan kingdom historical map"),
            T("qing_hs_champa", "占城", "The Remnant of Champa",
              "Shelter the last Cham lords of the Annamese coast. Costs #Y 20#! political influence.",
              "The last Cham lords are sheltered under the wing.",
              ("pol", 20), 10, False, "Map Kingdom of Champa 1380"),
            T("qing_hs_tributary_court", "萬邦來朝", "The Grand Tributary Court",
              "Convene the grand tributary court where every vassal-realm renders homage. Costs #Y 70#! treasury.",
              "The grand tributary court gathers every vassal-realm in homage.",
              ("trs", 70), 14, True, "Wanguo Laichao"),
        ],
    },
    "japan": {
        "loc": "qing_japan_l_english.yml",
        "parent": "qing_jp_open_relations",
        "tasks": [
            T("qing_jp_trade_treaty", "通商條約", "A Treaty of Commerce",
              "Conclude a treaty of commerce with the Meiji government. Costs #Y 55#! treasury.",
              "A treaty of commerce is concluded with Japan.",
              ("trs", 55), 10, False, "Meiji treaty signing woodblock print"),
            T("qing_jp_students", "留日學生", "Students in Japan",
              "Send scholars to study Japan's swift path to modernity. Costs #Y 25#! political influence.",
              "Chinese scholars study Japan's path to modernity.",
              ("pol", 25), 10, False, "Meiji era students woodblock print"),
            T("qing_jp_arsenal", "兵工互市", "The Arsenal Accord",
              "Share the working of the modern arsenals between the two empires. Costs #Y 60#! treasury.",
              "The two empires share the working of modern arsenals.",
              ("trs", 60), 10, False, "Meiji period woodblock print"),
            T("qing_jp_navy_visit", "艦隊互訪", "The Fleet Visits",
              "Exchange fleet visits between the Beiyang and the Japanese navies. Costs #Y 25#! political influence.",
              "The Beiyang and Japanese fleets exchange visits.",
              ("pol", 25), 10, False, "Meiji Japan navy woodblock print"),
            T("qing_jp_telegraph", "海底電纜", "The Submarine Cable",
              "Lay a submarine telegraph cable across the eastern sea. Costs #Y 60#! treasury.",
              "A submarine cable joins the two empires across the sea.",
              ("trs", 60), 10, False, "submarine telegraph cable historical illustration"),
            T("qing_jp_formosa_accord", "台灣事宜", "The Formosa Question",
              "Settle the Formosa question that soured the two courts in 1874. Costs #Y 25#! political influence.",
              "The Formosa question between the courts is settled.",
              ("pol", 25), 11, False, "Taiwan Formosa historical map 19th century"),
            T("qing_jp_shanghai", "上海通商", "The Shanghai Trade",
              "Open the Shanghai trade to Japanese merchants under treaty. Costs #Y 55#! treasury.",
              "The Shanghai trade opens to Japanese merchants.",
              ("trs", 55), 10, False, "Shanghai Bund historical"),
            T("qing_jp_scholars", "漢學交流", "The Exchange of Scholars",
              "Renew the old exchange of Chinese learning between the courts. Costs #Y 20#! political influence.",
              "The exchange of Chinese learning is renewed.",
              ("pol", 20), 10, False, "Meiji era scholars woodblock print"),
            T("qing_jp_coal", "煤炭貿易", "The Coal Trade",
              "Open the coal trade that feeds both empires' steamers. Costs #Y 55#! treasury.",
              "The coal trade feeds both empires' steamers.",
              ("trs", 55), 10, False, "Japan coal mine Meiji"),
            T("qing_jp_asian_league", "亞細亞連帶", "The Pan-Asian League",
              "Sound out a league of the eastern peoples against the West. Costs #Y 25#! political influence.",
              "A league of the eastern peoples is sounded out.",
              ("pol", 25), 11, False, "Meiji emperor woodblock print"),
            T("qing_jp_shared_defence", "共禦西洋", "Common Defence",
              "Bind the two empires in a common defence of the eastern seas. Costs #Y 70#! treasury.",
              "The two empires bind themselves to a common defence of the East.",
              ("trs", 70), 14, True, "First Sino-Japanese War woodblock print"),
        ],
    },
    "japan_preperry": {
        "loc": "qing_japan_preperry_l_english.yml",
        "parent": "qing_jppre_nagasaki_channel",
        "tasks": [
            T("qing_jppre_copper", "長崎銅貿", "The Nagasaki Copper",
              "Deepen the Nagasaki copper trade that the Chinese junks have long plied. Costs #Y 55#! treasury.",
              "The Nagasaki copper trade is deepened.",
              ("trs", 55), 10, False, "Nagasaki Dejima historical painting"),
            T("qing_jppre_tosen", "唐船風說", "The Chinese-Ship Reports",
              "Gather the tosen fusetsugaki, the reports the Chinese ships bring of the wider world. Costs #Y 20#! political influence.",
              "The Chinese-ship reports of the wider world are gathered.",
              ("pol", 20), 10, False, "Edo period document scroll"),
            T("qing_jppre_rangaku", "蘭學", "Dutch Learning",
              "Study the rangaku, the Dutch learning that seeps through the Nagasaki gate. Costs #Y 25#! political influence.",
              "The Dutch learning of Nagasaki is studied.",
              ("pol", 25), 10, False, "Edo period woodblock print"),
            T("qing_jppre_satsuma", "薩摩藩", "The Satsuma Domain",
              "Treat quietly with Satsuma, the southern domain that trades past the shogun's ban. Costs #Y 25#! political influence.",
              "Satsuma trades quietly past the shogun's ban.",
              ("pol", 25), 10, False, "Satsuma domain samurai woodblock print"),
            T("qing_jppre_ryukyu_route", "琉球中繼", "The Ryukyu Relay",
              "Work the Ryukyu relay, the back-door to the closed realm. Costs #Y 55#! treasury.",
              "The Ryukyu relay opens a back-door to the closed realm.",
              ("trs", 55), 10, False, "Ryukyu kingdom historical painting"),
            T("qing_jppre_silk", "生絲貿易", "The Raw-Silk Trade",
              "Feed the raw-silk trade that the daimyo crave from China. Costs #Y 55#! treasury.",
              "The raw-silk trade to the daimyo flourishes.",
              ("trs", 55), 10, False, "Edo period silk woodblock print"),
            T("qing_jppre_shimonoseki", "下關海峽", "The Shimonoseki Strait",
              "Chart the Shimonoseki strait, the gate of the Inland Sea. Costs #Y 55#! treasury.",
              "The Shimonoseki strait is charted.",
              ("trs", 55), 10, False, "Shimonoseki Japan woodblock print"),
            T("qing_jppre_ezo_probe", "蝦夷探查", "The Probe of Ezo",
              "Send a quiet probe to Ezo, the northern isle the shogun scarcely holds. Costs #Y 20#! political influence.",
              "A quiet probe reaches the northern isle of Ezo.",
              ("pol", 20), 10, False, "Ezo Hokkaido old map"),
            T("qing_jppre_coast_watch", "海防警戒", "The Coastal Watch",
              "Set a watch on the eastern coast against the shogun's suspicion. Costs #Y 55#! treasury.",
              "A watch is set on the eastern coast.",
              ("trs", 55), 10, False, "Qing dynasty coastal defence map"),
            T("qing_jppre_shogun_letter", "致幕府書", "A Letter to the Shogun",
              "Send a letter of state to the shogun at Edo. Costs #Y 20#! political influence.",
              "A letter of state reaches the shogun at Edo.",
              ("pol", 20), 10, False, "Tokugawa shogunate document woodblock print"),
            T("qing_jppre_open_port", "開港交涉", "Negotiate an Open Port",
              "Press the bakufu, before the black ships come, to open a port to China. Costs #Y 70#! treasury.",
              "The bakufu is pressed to open a port before the black ships come.",
              ("trs", 70), 14, True, "Perry Black Ships woodblock print"),
        ],
    },
    "nanyang": {
        "loc": "qing_nanyang_l_english.yml",
        "parent": "qing_nanyang_champion",
        "tasks": [
            T("qing_nanyang_manila", "馬尼拉華商", "The Manila Chinese",
              "Take the Manila Chinese, thrice massacred by the Spaniards, under the wing. Costs #Y 25#! political influence.",
              "The Manila Chinese are taken under the imperial wing.",
              ("pol", 25), 11, False, "Manila galleon"),
            T("qing_nanyang_batavia", "巴達維亞", "The Batavia Chinese",
              "Shelter the Chinese of Batavia after the Dutch slaughter of 1740. Costs #Y 25#! political influence.",
              "The Chinese of Batavia are sheltered under the wing.",
              ("pol", 25), 11, False, "Batavia Dutch East Indies historical painting"),
            T("qing_nanyang_siam_trade", "暹羅米貿", "The Siam Rice Trade",
              "Open the Siam rice trade that feeds the southern provinces. Costs #Y 55#! treasury.",
              "The Siam rice trade feeds the southern provinces.",
              ("trs", 55), 10, False, "Siam junk trade"),
            T("qing_nanyang_annam", "安南通商", "The Annam Trade",
              "Deepen the trade with Annam along the tribute-road of the south. Costs #Y 55#! treasury.",
              "The trade with Annam deepens along the tribute-road.",
              ("trs", 55), 10, False, "Nguyen dynasty Vietnam painting"),
            T("qing_nanyang_singapore", "星洲", "The Straits Settlement",
              "Plant a foothold in the straits where the ocean roads cross. Costs #Y 60#! treasury.",
              "A foothold is planted where the ocean roads cross.",
              ("trs", 60), 10, False, "Singapore historical 19th century"),
            T("qing_nanyang_tin", "錫礦", "The Tin Mines of Malaya",
              "Master the tin mines of Malaya, worked by Chinese kongsi. Costs #Y 60#! treasury.",
              "The tin mines of Malaya are mastered by the kongsi.",
              ("trs", 60), 10, False, "Malaya tin mine historical illustration"),
            T("qing_nanyang_pepper", "胡椒貿易", "The Pepper Trade",
              "Take a share of the pepper trade of the archipelago. Costs #Y 55#! treasury.",
              "A share of the archipelago's pepper trade is secured.",
              ("trs", 55), 10, False, "Moluccas historical map"),
            T("qing_nanyang_secret_societies", "天地會", "The Overseas Brotherhoods",
              "Turn the overseas brotherhoods to the throne's cause abroad. Costs #Y 20#! political influence.",
              "The overseas brotherhoods are turned to the throne's cause.",
              ("pol", 20), 10, False, "Tiandihui secret society"),
            T("qing_nanyang_consuls", "南洋領事", "The South Seas Consuls",
              "Appoint consuls to protect the diaspora among the western colonies. Costs #Y 25#! political influence.",
              "Consuls are appointed to protect the diaspora.",
              ("pol", 25), 10, False, "Qing dynasty diplomats portrait"),
            T("qing_nanyang_fleet", "南洋巡師", "The South Seas Squadron",
              "Station a South Seas squadron to show the flag among the islands. Costs #Y 70#! treasury.",
              "A South Seas squadron shows the flag among the islands.",
              ("trs", 70), 14, True, "Chinese cruiser 1880s"),
        ],
    },
    "open_japan": {
        "loc": "qing_open_japan_l_english.yml",
        "parent": "qing_openjapan_arrive",
        "tasks": [
            T("qing_openjapan_satsuma", "薩摩", "The Satsuma Domain",
              "Treat with Satsuma, the great southern domain of Kyushu. Costs #Y 25#! political influence.",
              "Satsuma of the south receives the treasure fleet's envoys.",
              ("pol", 25), 10, False, "Satsuma domain samurai woodblock print"),
            T("qing_openjapan_choshu", "長州", "The Choshu Domain",
              "Reach Choshu, keeper of the western strait. Costs #Y 25#! political influence.",
              "Choshu of the western strait inclines to the fleet.",
              ("pol", 25), 10, False, "Choshu domain samurai woodblock print"),
            T("qing_openjapan_osaka", "大阪", "The Merchant City of Osaka",
              "Open the merchant city of Osaka, kitchen of the realm. Costs #Y 55#! treasury.",
              "The merchant city of Osaka is opened to trade.",
              ("trs", 55), 10, False, "Osaka castle woodblock print"),
            T("qing_openjapan_kyoto", "京都朝廷", "The Court at Kyoto",
              "Send an embassy to the imperial court at Kyoto. Costs #Y 25#! political influence.",
              "An embassy reaches the imperial court at Kyoto.",
              ("pol", 25), 11, False, "Kyoto imperial court woodblock print"),
            T("qing_openjapan_silver", "石見銀山", "The Iwami Silver",
              "Open the Iwami silver mines to the trade of the fleet. Costs #Y 60#! treasury.",
              "The Iwami silver mines feed the fleet's trade.",
              ("trs", 60), 11, False, "Iwami silver mine Japan"),
            T("qing_openjapan_sakai", "堺港", "The Port of Sakai",
              "Charter the free port of Sakai for the treasure trade. Costs #Y 55#! treasury.",
              "The free port of Sakai is chartered for the trade.",
              ("trs", 55), 10, False, "Sakai Japan woodblock print"),
            T("qing_openjapan_daimyo", "大名結盟", "Ally the Daimyo",
              "Bind the coastal daimyo to the fleet with gifts and treaties. Costs #Y 25#! political influence.",
              "The coastal daimyo are bound to the fleet.",
              ("pol", 25), 10, False, "Daimyo procession woodblock print"),
            T("qing_openjapan_buddhism", "禪宗交流", "The Zen Exchange",
              "Renew the Zen Buddhist exchange between the two lands. Costs #Y 20#! political influence.",
              "The Zen Buddhist exchange between the lands is renewed.",
              ("pol", 20), 10, False, "Japanese temple woodblock print"),
            T("qing_openjapan_swords", "日本刀貿", "The Sword Trade",
              "Open the trade in Japanese blades, prized across the sea. Costs #Y 55#! treasury.",
              "The trade in Japanese blades is opened.",
              ("trs", 55), 10, False, "Japanese sword smith woodblock print"),
            T("qing_openjapan_alliance", "中日盟約", "The Sino-Japanese Pact",
              "Seal a lasting pact between the throne and the realm of the rising sun. Costs #Y 70#! treasury.",
              "A lasting pact is sealed with the realm of the rising sun.",
              ("trs", 70), 14, True, "Yokohama harbour woodblock print"),
        ],
    },
    "reform": {
        "loc": "qing_reform_missions_l_english.yml",
        "parent": "qing_con_bureau",
        "tasks": [
            T("qing_con_railways", "鐵路國有", "The Railway Policy",
              "Bring the trunk railways under a single state hand. Costs #Y 60#! treasury.",
              "The trunk railways come under a single state hand.",
              ("trs", 60), 10, False, "Qing dynasty railway historical photograph"),
            T("qing_con_currency", "幣制改革", "The Currency Reform",
              "Reform the tangled currency onto a single silver standard. Costs #Y 60#! treasury.",
              "The currency is reformed onto a single silver standard.",
              ("trs", 60), 10, False, "Qing dynasty silver coin historical"),
            T("qing_con_police", "巡警制度", "The Modern Police",
              "Raise a modern police in the great cities. Costs #Y 55#! treasury.",
              "A modern police is raised in the great cities.",
              ("trs", 55), 10, False, "Late Qing police photograph"),
            T("qing_con_schools", "新式學堂", "The New Schools",
              "Found new-style schools across the provinces. Costs #Y 55#! treasury.",
              "New-style schools are founded across the provinces.",
              ("trs", 55), 10, False, "Late Qing new school photograph"),
            T("qing_con_press", "報館開放", "The Free Press",
              "Loosen the throne's hand upon the newspapers. Costs #Y 25#! political influence.",
              "The throne's hand upon the newspapers is loosened.",
              ("pol", 25), 10, False, "Late Qing newspaper"),
            T("qing_con_cabinet", "責任內閣", "The Responsible Cabinet",
              "Erect a responsible cabinet answerable for the ministries. Costs #Y 25#! political influence.",
              "A responsible cabinet answers for the ministries.",
              ("pol", 25), 11, False, "Qing dynasty government office painting"),
            T("qing_con_provincial", "諮議局", "The Provincial Assemblies",
              "Convene the provincial deliberative assemblies. Costs #Y 25#! political influence.",
              "The provincial deliberative assemblies convene.",
              ("pol", 25), 11, False, "Qing dynasty assembly hall historical"),
            T("qing_con_banking", "戶部銀行", "The State Bank",
              "Charter a state bank under the Board of Revenue. Costs #Y 60#! treasury.",
              "A state bank is chartered under the Board of Revenue.",
              ("trs", 60), 10, False, "Qing dynasty bank note historical"),
            T("qing_con_census", "人口普查", "The Imperial Census",
              "Order a modern census of the empire's multitudes. Costs #Y 55#! treasury.",
              "A modern census counts the empire's multitudes.",
              ("trs", 55), 10, False, "Qing dynasty household register"),
            T("qing_con_manchu_han", "滿漢一體", "Manchu and Han as One",
              "End the old distinctions between Manchu and Han before the law. Costs #Y 25#! political influence.",
              "The old distinctions of Manchu and Han are ended before the law.",
              ("pol", 25), 14, True, "Qing dynasty imperial edict document"),
        ],
    },
    "selfstrengthening": {
        "loc": "qing_selfstrengthening_l_english.yml",
        "parent": "qing_ss_zongli",
        "tasks": [
            T("qing_ss_hanyang", "漢陽鐵廠", "The Hanyang Ironworks",
              "Raise the Hanyang ironworks, first great foundry of the empire. Costs #Y 65#! treasury.",
              "The Hanyang ironworks pour the empire's first modern steel.",
              ("trs", 65), 11, False, "Hanyang Arsenal China historical"),
            T("qing_ss_kaiping", "開平煤礦", "The Kaiping Coal Mines",
              "Open the Kaiping coal mines to feed the arsenals and the fleet. Costs #Y 60#! treasury.",
              "The Kaiping coal mines feed the arsenals and the fleet.",
              ("trs", 60), 10, False, "coal mine historical photograph"),
            T("qing_ss_cotton_mill", "機器織布", "The Cotton Mill",
              "Build the Shanghai machine-weaving mill, herald of the new industry. Costs #Y 70#! treasury.",
              "The Shanghai cotton mill heralds the new industry.",
              ("trs", 70), 13, True, "Shanghai cotton mill historical photograph"),
        ],
    },
    "settle_frontier": {
        "loc": "qing_settle_frontier_l_english.yml",
        "parent": "qing_settle_policy",
        "tasks": [
            T("qing_settle_heilongjiang", "黑龍江墾", "The Amur Reclamation",
              "Throw open Heilongjiang to the plough against the Russian tide. Costs #Y 60#! treasury.",
              "Heilongjiang is thrown open to the plough.",
              ("trs", 60), 11, False, "Amur river historical map"),
            T("qing_settle_jilin", "吉林屯墾", "The Jilin Colonies",
              "Settle the black earth of Jilin with military-farm colonies. Costs #Y 55#! treasury.",
              "The black earth of Jilin fills with farm colonies.",
              ("trs", 55), 10, False, "Manchuria historical map 18th century"),
            T("qing_settle_amur_guard", "璦琿戍邊", "The Aigun Guard",
              "Set a river-guard on the Amur at Aigun. Costs #Y 55#! treasury.",
              "A river-guard holds the Amur at Aigun.",
              ("trs", 55), 10, False, "Aigun Amur river historical"),
            T("qing_settle_khalkha", "喀爾喀", "The Khalkha Mongols",
              "Bind the Khalkha Mongols closer to the throne. Costs #Y 20#! political influence.",
              "The Khalkha Mongols are bound closer to the throne.",
              ("pol", 20), 10, False, "Mongol noble painting"),
            T("qing_settle_chahar", "察哈爾", "The Chahar Banners",
              "Order the Chahar banners of the near steppe. Costs #Y 20#! political influence.",
              "The Chahar banners of the near steppe are ordered.",
              ("pol", 20), 10, False, "Mongol warrior painting"),
            T("qing_settle_ranches", "牧場馬政", "The Horse-Ranches",
              "Restore the imperial horse-ranches of the frontier. Costs #Y 55#! treasury.",
              "The imperial horse-ranches of the frontier are restored.",
              ("trs", 55), 10, False, "Qing dynasty horses painting Castiglione"),
            T("qing_settle_kulun", "庫倫", "The Seat at Urga",
              "Strengthen the amban's seat at Urga on the northern road. Costs #Y 20#! political influence.",
              "The amban's seat at Urga is strengthened.",
              ("pol", 20), 10, False, "Urga Mongolia historical illustration"),
            T("qing_settle_ginseng", "人參採辦", "The Ginseng Monopoly",
              "Order the ginseng monopoly of the Manchurian forests. Costs #Y 55#! treasury.",
              "The ginseng monopoly of the forests is ordered.",
              ("trs", 55), 10, False, "ginseng plant illustration"),
            T("qing_settle_railway_east", "東清鐵路", "The Eastern Railway",
              "Drive a railway across the black-earth frontier. Costs #Y 65#! treasury.",
              "A railway crosses the black-earth frontier.",
              ("trs", 65), 11, False, "Qing dynasty railway historical photograph"),
            T("qing_settle_new_province", "行省設治", "Erect a Frontier Province",
              "Turn the settled frontier into a regular province of the empire. Costs #Y 70#! treasury.",
              "The settled frontier is made a regular province of the empire.",
              ("trs", 70), 14, True, "Qing empire historical map 18th century"),
        ],
    },
    "summer_palace": {
        "loc": "qing_summer_palace_l_english.yml",
        "parent": "qing_sp_yuanmingyuan",
        "tasks": [
            T("qing_sp_forbidden_city", "紫禁重修", "Restore the Forbidden City",
              "Renew the halls of the Forbidden City in their old splendour. Costs #Y 60#! treasury.",
              "The halls of the Forbidden City shine in their old splendour.",
              ("trs", 60), 11, False, "Forbidden City Qing painting"),
            T("qing_sp_chengde", "承德避暑", "The Chengde Retreat",
              "Restore the mountain resort at Chengde, summer seat of the emperors. Costs #Y 55#! treasury.",
              "The mountain resort at Chengde is restored.",
              ("trs", 55), 10, False, "Chengde mountain resort Qing painting"),
            T("qing_sp_jade_spring", "玉泉山", "Jade Spring Hill",
              "Adorn Jade Spring Hill, source of the palace waters. Costs #Y 55#! treasury.",
              "Jade Spring Hill is adorned anew.",
              ("trs", 55), 10, False, "Jade Spring Hill Beijing"),
            T("qing_sp_astronomy", "觀象台", "The Observatory",
              "Refit the ancient observatory with the Jesuits' instruments. Costs #Y 25#! political influence.",
              "The ancient observatory is refitted with new instruments.",
              ("pol", 25), 10, False, "Beijing ancient observatory historical engraving"),
            T("qing_sp_clocks", "自鳴鐘", "The Clock Collection",
              "Assemble the great collection of European chiming clocks. Costs #Y 60#! treasury.",
              "The great collection of European clocks is assembled.",
              ("trs", 60), 10, False, "Qing dynasty clock museum"),
            T("qing_sp_gardens_west", "西郊三山", "The Three Western Hills",
              "Lay out the three hills and five gardens of the western suburb. Costs #Y 60#! treasury.",
              "The three hills and five gardens of the west are laid out.",
              ("trs", 60), 10, False, "Old Summer Palace Yuanmingyuan engraving"),
            T("qing_sp_calligraphy", "三希堂", "The Hall of Three Rarities",
              "Gather the imperial calligraphy in the Hall of Three Rarities. Costs #Y 20#! political influence.",
              "The imperial calligraphy is gathered in the Hall of Three Rarities.",
              ("pol", 20), 10, False, "Chinese calligraphy Qianlong museum"),
            T("qing_sp_bronzes", "十二生肖", "The Zodiac Fountains",
              "Cast the twelve zodiac bronzes of the great water-clock fountain. Costs #Y 55#! treasury.",
              "The twelve zodiac bronzes crown the water-clock fountain.",
              ("trs", 55), 10, False, "Xiyang Lou Yuanmingyuan engraving"),
            T("qing_sp_lantern", "元宵燈會", "The Lantern Festival",
              "Hold the great lantern festival within the palace grounds. Costs #Y 20#! political influence.",
              "The great lantern festival lights the palace grounds.",
              ("pol", 20), 10, False, "Qing dynasty lantern festival painting"),
            T("qing_sp_grand_garden", "萬園之園", "The Garden of Gardens",
              "Complete the Garden of Gardens, wonder of the eastern world. Costs #Y 70#! treasury.",
              "The Garden of Gardens stands complete, wonder of the eastern world.",
              ("trs", 70), 14, True, "Old Summer Palace Yuanmingyuan engraving"),
        ],
    },
    "taiping": {
        "loc": "qing_taiping_missions_l_english.yml",
        "parent": "qing_hk_channel",
        "tasks": [
            T("qing_hk_xiang_army", "湘軍", "The Xiang Army",
              "Let Zeng Guofan raise the Xiang Army of Hunan gentry and militia. Costs #Y 60#! treasury.",
              "Zeng Guofan raises the Xiang Army of Hunan.",
              ("trs", 60), 12, False, "Zeng Guofan portrait Qing"),
            T("qing_hk_huai_army", "淮軍", "The Huai Army",
              "Let Li Hongzhang raise the Huai Army to relieve the lower Yangtze. Costs #Y 60#! treasury.",
              "Li Hongzhang raises the Huai Army for the lower Yangtze.",
              ("trs", 60), 12, False, "Li Hongzhang portrait Qing"),
            T("qing_hk_anqing", "安慶會戰", "The Siege of Anqing",
              "Take Anqing, the river-gate to the rebel capital. Costs #Y 55#! treasury.",
              "Anqing, the gate to the rebel capital, is taken.",
              ("trs", 55), 11, False, "Qing ambush Taiping Army Wangjiakou 1854"),
            T("qing_hk_suzhou", "蘇州克復", "The Recapture of Suzhou",
              "Retake Suzhou, jewel of the Yangtze delta. Costs #Y 55#! treasury.",
              "Suzhou, jewel of the delta, is retaken.",
              ("trs", 55), 11, False, "Suzhou garden painting"),
            T("qing_hk_hangzhou", "杭州", "The Fall of Hangzhou",
              "Wrest Hangzhou from the rebel grip. Costs #Y 55#! treasury.",
              "Hangzhou is wrested from the rebel grip.",
              ("trs", 55), 11, False, "West Lake Hangzhou painting"),
            T("qing_hk_nian", "捻軍", "The Nian Rebels",
              "Ride down the Nian horsemen of the northern plain. Costs #Y 55#! treasury.",
              "The Nian horsemen of the plain are ridden down.",
              ("trs", 55), 10, False, "Qing cavalry battle painting"),
            T("qing_hk_gordon", "戈登常勝", "Gordon's Command",
              "Set Gordon over the Ever Victorious Army before Shanghai. Costs #Y 25#! political influence.",
              "Gordon takes command of the Ever Victorious Army.",
              ("pol", 25), 11, False, "Ever Victorious Army"),
            T("qing_hk_militia", "團練鄉勇", "The Local Militias",
              "Raise the tuanlian militias across the loyal countryside. Costs #Y 55#! treasury.",
              "The tuanlian militias rise across the loyal countryside.",
              ("trs", 55), 10, False, "Qing dynasty soldiers painting"),
            T("qing_hk_grain_south", "東南財賦", "The Southern Revenues",
              "Restore the southeastern revenues that fund the war. Costs #Y 55#! treasury.",
              "The southeastern revenues that fund the war are restored.",
              ("trs", 55), 10, False, "Chinese grain barge painting"),
            T("qing_hk_restore_order", "克復金陵", "Retake Nanjing",
              "Storm the Heavenly Capital at Nanjing and restore the order of Heaven. Costs #Y 70#! treasury.",
              "The Heavenly Capital falls and the order of Heaven is restored.",
              ("trs", 70), 15, True, "Nanjing Taiping historical painting"),
        ],
    },
    "xinjiang": {
        "loc": "qing_xinjiang_missions_l_english.yml",
        "parent": "qing_xj_governorship",
        "tasks": [
            T("qing_xj_zuo_zongtang", "左宗棠西征", "Zuo Zongtang's March",
              "Send Zuo Zongtang west, his coffins carried before the army. Costs #Y 65#! treasury.",
              "Zuo Zongtang marches west to reclaim the frontier.",
              ("trs", 65), 12, False, "Zuo Zongtang portrait Qing"),
            T("qing_xj_yakub_beg", "阿古柏", "The Fall of Yakub Beg",
              "Break the emirate of Yakub Beg at Kashgar. Costs #Y 60#! treasury.",
              "The emirate of Yakub Beg is broken.",
              ("trs", 60), 12, False, "Yakub Beg Kashgar historical"),
            T("qing_xj_ili_return", "伊犁交涉", "The Return of Ili",
              "Wrest the Ili valley back from Russia at the treaty table. Costs #Y 25#! political influence.",
              "The Ili valley is wrested back from Russia.",
              ("pol", 25), 12, False, "Ili valley Xinjiang historical map"),
            T("qing_xj_urumqi", "迪化", "The Seat at Dihua",
              "Set the new governorship's seat at Dihua. Costs #Y 55#! treasury.",
              "The governorship's seat is set at Dihua.",
              ("trs", 55), 10, False, "Urumqi Dihua Xinjiang historical"),
            T("qing_xj_kashgar_gov", "喀什噶爾道", "The Kashgar Circuit",
              "Erect the Kashgar circuit over the western oases. Costs #Y 55#! treasury.",
              "The Kashgar circuit governs the western oases.",
              ("trs", 55), 10, False, "Kashgar historical"),
            T("qing_xj_tarim", "塔里木屯田", "The Tarim Colonies",
              "Plant military-farm colonies around the Tarim basin. Costs #Y 55#! treasury.",
              "Military-farm colonies ring the Tarim basin.",
              ("trs", 55), 10, False, "Qing dynasty farming painting"),
            T("qing_xj_cotton", "棉花種植", "The Cotton Fields",
              "Sow the oasis fields with cotton for the looms of the east. Costs #Y 55#! treasury.",
              "The oasis fields are sown with cotton.",
              ("trs", 55), 10, False, "cotton field historical illustration"),
            T("qing_xj_hexi", "河西走廊", "The Hexi Corridor",
              "Secure the Hexi corridor, the supply-road into the west. Costs #Y 55#! treasury.",
              "The Hexi corridor supply-road is secured.",
              ("trs", 55), 10, False, "Hexi corridor Gansu historical map"),
            T("qing_xj_muslim_policy", "回民安撫", "The Muslim Policy",
              "Settle a just policy toward the Muslim peoples of the west. Costs #Y 25#! political influence.",
              "A just policy is settled toward the Muslim peoples of the west.",
              ("pol", 25), 11, False, "Uyghur historical"),
            T("qing_xj_new_province", "新疆建省", "Erect Xinjiang Province",
              "Turn the New Dominion into a regular province of the empire. Costs #Y 70#! treasury.",
              "The New Dominion is made a regular province of the empire.",
              ("trs", 70), 15, True, "Qing empire historical map Xinjiang"),
        ],
    },
}


# Flat query dict merged into gen_mission_icons' CONCEPT_QUERY (see mission_task_queries.py).
CONTENT_QUERY = {t.key: t.query for tree in TREES.values() for t in tree["tasks"]}
